// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPXSx83_5rBSr8XWN41WnQEYoaPfLjtM',
    appId: '1:899708379709:web:231e1fd331ecb1e1b38054',
    messagingSenderId: '899708379709',
    projectId: 'pharmanow-754a7',
    authDomain: 'pharmanow-754a7.firebaseapp.com',
    storageBucket: 'pharmanow-754a7.firebasestorage.app',
    measurementId: 'G-M6RJ7T6RSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWX44ZDBZuV9Yj_rp1kL4Ydn9HbQuzfg',
    appId: '1:899708379709:android:73edc66c9ff31004b38054',
    messagingSenderId: '899708379709',
    projectId: 'pharmanow-754a7',
    storageBucket: 'pharmanow-754a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9uimDRQ33liR8jMOy0JkJlttgO0Xhhg',
    appId: '1:899708379709:ios:4f13eb3f90efe2a7b38054',
    messagingSenderId: '899708379709',
    projectId: 'pharmanow-754a7',
    storageBucket: 'pharmanow-754a7.firebasestorage.app',
    androidClientId: '899708379709-ugjfp5rjpcnlrs596cvlcvs7r9nd7scu.apps.googleusercontent.com',
    iosClientId: '899708379709-4bv41ia8bg3lnc5vqdsattpqr48gfnvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmaDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9uimDRQ33liR8jMOy0JkJlttgO0Xhhg',
    appId: '1:899708379709:ios:4f13eb3f90efe2a7b38054',
    messagingSenderId: '899708379709',
    projectId: 'pharmanow-754a7',
    storageBucket: 'pharmanow-754a7.firebasestorage.app',
    androidClientId: '899708379709-ugjfp5rjpcnlrs596cvlcvs7r9nd7scu.apps.googleusercontent.com',
    iosClientId: '899708379709-4bv41ia8bg3lnc5vqdsattpqr48gfnvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmaDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLPXSx83_5rBSr8XWN41WnQEYoaPfLjtM',
    appId: '1:899708379709:web:1561b9ef867653deb38054',
    messagingSenderId: '899708379709',
    projectId: 'pharmanow-754a7',
    authDomain: 'pharmanow-754a7.firebaseapp.com',
    storageBucket: 'pharmanow-754a7.firebasestorage.app',
    measurementId: 'G-X1VX8GY8DS',
  );
}
